Repository jaw41/WpfApp, pull requests merged in 2020-06, with the labels that each got.

#2 Adding material design
  README.txt
  WpfApp/App.xaml
  WpfApp/View/DataVisualiser.xaml
  WpfApp/View/MainWindow.xaml
  WpfApp/View/NotepadView.xaml
  WpfApp/ViewModel/DataVisualiserViewModel.cs
  WpfApp/ViewModel/Interfaces/INavigatable.cs
  WpfApp/ViewModel/MainViewModel.cs
  WpfApp/ViewModel/NotepadViewModel.cs
  WpfApp/WpfApp.csproj
Labels: User Interface

#8 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: deployment

#7 README changes
  README
  README.txt
Labels: documentation
